@startuml Zustandsdiagramm
[*] --> StartMenü

state StartMenü {
  [*] --> StartMenü: Zeige Startmenü
  StartMenü --> Login: Klicke "Login"
  StartMenü --> BuchSuche: Klicke "Buch suchen"
  StartMenü --> BuchErstellen: Klicke "Buch erstellen"
}

state Login {
  Login --> BuchErstellen: Klicke "Buch erstellen"
  Login --> BuchSuche: Klicke "Buch suchen"
  Login --> StartMenü: Klicke "Home"
}

state BuchSuche {
  BuchSuche --> BuchDetails: Suche abschicken
  BuchSuche --> Login: Klicke "Login"
  BuchSuche --> BuchErstellen: Klicke "Buch erstellen"
  BuchSuche --> StartMenü: Klicke "Home"
}

state BuchErstellen {
  BuchErstellen --> BuchErstellt: Klicke "Buch erstellen"
  BuchErstellen --> StartMenü: Klicke "Home"
}

state BuchDetails {
}

state BuchErstellt {
}

StartMenü -down-> Login
Login -down-> BuchSuche
BuchSuche -down-> BuchErstellen

StartMenü: Zeige Startmenü
Login: Zeige Anmeldeseite
BuchSuche: Zeige Buchsuche-Seite
BuchErstellen: Zeige Bucherstellungsseite
BuchDetails: Zeige Buchdetails (ISBN, Titel, Buchtyp, Version, Art)
BuchErstellt: Zeige Bestätigung für Bucherstellung
@enduml