@startuml Zustandsdiagramm

skinparam state {
    BackgroundColor LightGrey
}

state index {
    [*] --> Home
    
    state Verteilung <<choice>>
    Home --> Verteilung
    
    Verteilung --> auth: Button "Login"
    auth --> Verteilung: Button "Home"

    Verteilung --> create: Button "Buch anlegen"
    create --> Verteilung: Button "Home"
    Verteilung --> root: Button "Bücher suchen"
    root --> Verteilung: Button "Home"


    index: jwt roles expiration
  
    state "Login" as auth {
        Anmeldeformular: username
        Anmeldeformular: password
        state Anmeldergebnis <<choice>>

        [*] --> Anmeldeformular
        Anmeldeformular --> Anmeldergebnis
        Anmeldergebnis --> AnmeldeFehler: Fehlerhafte Daten
        Anmeldergebnis --> [*]: Erfolg
    }

    state "Buch erstellen" as create {
        Anlegeformular: form
        state Anmeldeergebnis <<choice>>

        [*] --> Anlegeformular
        Anlegeformular --> Anmeldeergebnis
        Anmeldeergebnis --> AnlegeFehler: Fehlerhafte Daten
        Anmeldeergebnis --> [*]: Erfolg
    }

    state "Buch suchen" as root {
        Suchformular: suchkriterien
        state Suchergebnis <<choice>>

        [*] --> Suchformular
        Suchformular --> Bestätigung: Eingabe Id "Id eingeben"
        Bestätigung --> Waiting: Button "Suche Buch"
        Waiting --> BookSearch: Suche nach Id
        BookSearch --> Suchergebnis
        Suchergebnis --> GefundeneBuecher: 1 Buch gefunden
        Suchergebnis --> KeineBuecher: Keine Bücher
        GefundeneBuecher -->  DetailsBuch: Details angezeigt
    }



}

@enduml
